### ISSUE TITLE
make: *** No rule to make target `vpx_config.h', needed by `vpx_config.asm'.  Stop.`

### ISSUE THREAD

**Issue by bingdiao** [ryujt/vpx-android#1]
저는 중국인입니다. 소프트웨어로 한글을 번역해 드립니다. 도움을 청하고 싶습니다.
제가 당신의 창고를 사용했는데, 어긋났다는 것을, 보고 내용이 캡처였습니다. 좀 봐주실 수 없나요?

`Build command failed.
Error while executing process E:\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\ToDesk\VPX\src\main\jni\Android.mk NDK_APPLICATION_MK=F:\ToDesk\VPX\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=F:/ToDesk/VPX/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib\armeabi-v7a" >NUL 2>NUL || rem
E:/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdbserver"
copy /b/y "E:\Sdk\ndk-bundle\build\\..\prebuilt\android-arm\gdbserver\gdbserver" "F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib\armeabi-v7a\gdbserver" > NUL
E:/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbsetup       ": "F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup"
E:/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path F:/ToDesk/VPX/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a" > F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup
E:/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory E:/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot E:/Sdk/ndk-bundle/build//../sources/cxx-stl/system F:/ToDesk/VPX/src/main/jni" >> F:\ToDesk\VPX\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup
echo "    [CREATE] vp8_rtcd.h"
F:/ToDesk/VPX/src/main/jni/libvpx/build/make/rtcd.pl --arch=armv7 --sym=vp8_rtcd --config=F:/ToDesk/VPX/src/main/jni/libs-armv7-android-gcc.mk  F:/ToDesk/VPX/src/main/jni/libvpx/vp8/common/rtcd_defs.pl > vp8_rtcd.h
echo "    [CREATE] vp9_rtcd.h"
F:/ToDesk/VPX/src/main/jni/libvpx/build/make/rtcd.pl --arch=armv7 --sym=vp9_rtcd --config=F:/ToDesk/VPX/src/main/jni/libs-armv7-android-gcc.mk  F:/ToDesk/VPX/src/main/jni/libvpx/vp9/common/vp9_rtcd_defs.pl > vp9_rtcd.h
echo "    [CREATE] vpx_scale_rtcd.h"
F:/ToDesk/VPX/src/main/jni/libvpx/build/make/rtcd.pl --arch=armv7 --sym=vpx_scale_rtcd --config=F:/ToDesk/VPX/src/main/jni/libs-armv7-android-gcc.mk  F:/ToDesk/VPX/src/main/jni/libvpx/vpx_scale/vpx_scale_rtcd.pl > vpx_scale_rtcd.h
echo "    [CREATE] vpx_dsp_rtcd.h"
F:/ToDesk/VPX/src/main/jni/libvpx/build/make/rtcd.pl --arch=armv7 --sym=vpx_dsp_rtcd --config=F:/ToDesk/VPX/src/main/jni/libs-armv7-android-gcc.mk  F:/ToDesk/VPX/src/main/jni/libvpx/vpx_dsp/vpx_dsp_rtcd_defs.pl > vpx_dsp_rtcd.h

process_begin: CreateProcess(NULL, "", ...) failed.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `vpx_config.h', needed by `vpx_config.asm'.  Stop.`

**Comment by ryujt** [comment]
I tried arm7 only.
If you need other platforms, check "https://github.com/cmeng-git/vpx-android.git".
I didn't tried that repository, btw it looks like support what you want.

**Comment by ryujt** [comment]
I have push the new code just now.
btw I didn't those outputs on my device.
